[package]
name = "mqtt_5"
version = "0.1.0"
authors = ["Ethan Spurlock <ethan@spurlock.io>"]
edition = "2018"


[dependencies]
packattack = { path = "C:\\Users\\Ethan\\Desktop\\packattack" }
packattack_derive = { path = "C:\\Users\\Ethan\\Desktop\\packattack-derive" }